# Use Node or Bun base image
FROM oven/bun:latest as base
WORKDIR /usr/src/app

# Install dependencies
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile

# Copy source
COPY . .

# Expose port
EXPOSE 3000

# Run the app
CMD ["bun", "run", "start"]
